added docs for updating and deleting book logs
Code-4-Community/c4c-dev-docs pull request #60
Opened 2021-05-13 14:59 UTC by DerekL27

added docs for deleting, updated responses for updating

2021-05-14 04:55 UTC, jtavera235 commented
Looks good!

2021-05-14 04:56 UTC, jtavera235 approved these changes

2021-05-18 20:05 UTC, justinkonecny requested changes

2021-05-18 20:05 UTC, justinkonecny commented on docs/hats/api-spec-school-books.md
> +`400 Does not exist` : School or Book Log does not exist
`400 Bad Request`

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

2021-05-18 20:05 UTC, justinkonecny commented on docs/hats/api-spec-school-books.md
> +`400 Does not exist` : School or Book Log does not exist
`400 Bad Request`

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

2021-06-29 22:23 UTC, justinkonecny approved these changes

2021-06-29 22:23 UTC, merged